### ISSUE TITLE
Not working for Next.js typical file paths

### ISSUE THREAD

**Issue by wrgrant** [ctf0/local-history#6]
In Next.js, you'll typically have folders that contain the following characters `(, [, ..., ], )`

This seems to be causing issues with the extension. As in a Next.js project structure, Local History picks up changes for files at the root of the project, but it does not pick up any changes contained as direct, or descendent children of folders containing the characters mentioned above.

Here is [some documentation](https://nextjs.org/docs/getting-started/project-structure) on the various types of folder structures.

I'm guessing that somewhere in [internalDecodeFile](https://github.com/ctf0/local-history/blob/14b5a9302ae9b521e27405014e00fc0ce1a57e0b/src/Provider/Controller.ts#L395) this breaks expected behavior.

I will probably take a look at this sometime soon, but just in case you know off the top of your head how to fix this easily, I'm sending in the issue.

**Comment by ctf0** [comment]
i havent tried that b4, but if the file save doesnt work then we should start with https://github.com/ctf0/local-history/blob/14b5a9302ae9b521e27405014e00fc0ce1a57e0b/src/Provider/Controller.ts#L173 
and figure out why we cant replicate the file path structure under the `.history` folder.

of if i misunderstand your point, plz give me some steps to reproduce with.

**Comment by wrgrant** [comment]
Looking into this further, the files *are* saved in the `.history` directory correctly.

But for these nested files, when they are selected as the active editor file, the `Local History` tree view says `No History`, but it does show history for the file that is not nested under these folders.

I will setup a minimum replicatable repo in a bit here and send to you.

**Comment by wrgrant** [comment]
Alright, tested some more. It seems to be specifically any folders that contain a square bracket `[someFolder]` that cause the issue.

I created a test repo here. Pretty much anything outside a square bracket works.
https://github.com/wrgrant/bug-report

Interestingly, the files are being captured in the `.history` folder no matter what.
They just aren't being shown in the history browser.
Trying to open some of the nested ones will cause the browser to hang. But I can't always reproduce that.

**Comment by ctf0** [comment]
ok i tested it and atm the files are being saved correctly but not listed in the browser.

am a bit busy atm but will see what i can do in the next days.

in the meantime, have u tried the builtin feature `timeline` ?
